import { UserRole } from '../users/entities/user.entity';

export const goldenUsers = [
    {
        email: 'superadmin@clone.com',
        password: 'Password123!', // Seeder servisinde bunu hash'leyip kaydedeceğiz
        firstName: 'Super',
        lastName: 'Admin',
        role: UserRole.SUPERADMIN,
    },
    {
        email: 'admin@clone.com',
        password: 'Password123!',
        firstName: 'Normal',
        lastName: 'Admin',
        role: UserRole.ADMIN,
    },
    {
        email: 'customer@clone.com',
        password: 'Password123!',
        firstName: 'Sadık',
        lastName: 'Müşteri',
        role: UserRole.CUSTOMER,
    },
];

export const goldenBooks = [
    {
        title: 'Saatleri Ayarlama Enstitüsü',
        author: 'Ahmet Hamdi Tanpınar',
        price: 185.00,
        stock: 50,
        isbn: '9789750802636',
        coverImageUrl: '/uploads/covers/saatleri-ayarlama-enstitusu.jpg',
    },
    {
        title: 'Benim Adım Kırmızı (My Name is Red)',
        author: 'Orhan Pamuk',
        price: 210.00,
        stock: 30,
        isbn: '9789750800000',
        coverImageUrl: '/uploads/covers/benim-adim-kirmizi.jpg',
    },
    {
        title: 'Nutuk',
        author: 'Mustafa Kemal Atatürk',
        price: 195.50,
        stock: 45,
        isbn: '9789750800001',
        coverImageUrl: '/uploads/covers/nutuk.jpg',
    },
    {
        title: 'Tutunamayanlar',
        author: 'Oğuz Atay',
        price: 240.00,
        stock: 28,
        isbn: '9789754700112',
        coverImageUrl: '/uploads/covers/tutunamayanlar.jpg',
    },
    {
        title: 'Kürk Mantolu Madonna',
        author: 'Sabahattin Ali',
        price: 145.90,
        stock: 60,
        isbn: '9789753638027',
        coverImageUrl: '/uploads/covers/kurk-mantolu-madonna.jpg',
    },
    {
        title: 'İnce Memed',
        author: 'Yaşar Kemal',
        price: 220.00,
        stock: 35,
        isbn: '9789750801234',
        coverImageUrl: '/uploads/covers/ince-memed.jpg',
    },
    {
        title: 'Serenad',
        author: 'Zülfü Livaneli',
        price: 175.00,
        stock: 42,
        isbn: '9786050900123',
        coverImageUrl: '/uploads/covers/serenad.jpg',
    },
    {
        title: 'Kuyucaklı Yusuf',
        author: 'Sabahattin Ali',
        price: 168.75,
        stock: 38,
        isbn: '9786051111111',
        coverImageUrl: '/uploads/covers/kuyucakli-yusuf.jpg',
    },
    {
        title: 'Masumiyet Müzesi',
        author: 'Orhan Pamuk',
        price: 230.00,
        stock: 25,
        isbn: '9789750820002',
        coverImageUrl: '/uploads/covers/masumiyet-muzesi.jpg',
    },
    {
        title: 'Puslu Kıtalar Atlası',
        author: 'İhsan Oktay Anar',
        price: 190.00,
        stock: 40,
        isbn: '9789754709009',
        coverImageUrl: '/uploads/covers/puslu-kitalar-atlasi.jpg',
    },
    {
        title: 'Kinyas ve Kayra',
        author: 'Hakan Günday',
        price: 205.50,
        stock: 22,
        isbn: '9789755703006',
        coverImageUrl: '/uploads/covers/kinyas-ve-kayra.jpg',
    },
    {
        title: 'Hayvan Çiftliği',
        author: 'George Orwell',
        price: 135.00,
        stock: 70,
        isbn: '9789750719385',
        coverImageUrl: '/uploads/covers/hayvan-ciftligi.jpg',
    },
    {
        title: '1984',
        author: 'George Orwell',
        price: 155.00,
        stock: 55,
        isbn: '9789750718531',
        coverImageUrl: '/uploads/covers/1984.jpg',
    },
    {
        title: 'Simyacı',
        author: 'Paulo Coelho',
        price: 149.99,
        stock: 48,
        isbn: '9789750726437',
        coverImageUrl: '/uploads/covers/simyaci.jpg',
    },
    {
        title: 'Suç ve Ceza',
        author: 'Fyodor Dostoyevski',
        price: 215.00,
        stock: 33,
        isbn: '9789754589021',
        coverImageUrl: '/uploads/covers/suc-ve-ceza.jpg',
    }
];